### ISSUE TITLE
[BUG] Away status problem using Round brackets ( )

### ISSUE THREAD

**Issue by PythonInvasion** [ZerGo0/streamdeck-teamspeak3integration#1]
Hello. I can't set up Away status with brackets.

It works when i write "restroom\s\\(my text\)"

**Comment by ZerGo0** [comment]
Fixed in v1.5: https://github.com/ZerGo0/streamdeck-teamspeak3integration/blob/b75047115529e5e8dfffb13ce050ff1b93a42904/streamdeck-teamspeak3integration/Helpers/TeamSpeak3Telnet.cs#L274

Thanks for reporting it.
