### ISSUE TITLE
Switching Channels

### ISSUE THREAD

**Issue by mrwinnie-911** [ZerGo0/streamdeck-teamspeak3integration#10]
I have alot of Sub channels in my server with the same name and stuff and when i change channels with the button. Its always the first channel with that name. Can you change the API hook to look for the Channel ID # ? That is the only thing that will remain different from the other channels. Thanks!

**Comment by ZerGo0** [comment]
Sorry for the extremely late response, totally forgot about this. Added support for it in the next update.
