### ISSUE TITLE
StreamDeck TS3 Title Restart Bug

### ISSUE THREAD

**Issue by joolaas** [ZerGo0/streamdeck-teamspeak3integration#12]
Hey there,

i have an issue with your ts3 streamdeck integration.

When i place the ts3 mute on my deck for example and I remove the title "TeamSpeak
Mic Mute" of this deck icon so it has not title and then restart my PC/StreamDeck. Then after the restart the title is back there and I have to remove it manually.

Would it be possible for you to fix this little issue, because it is a bit exhausting to remove the title every time after a restart...

**Comment by PythonInvasion** [comment]
Hello. I got the same issue. This is no problem from TS3-Plugin.

If you want remove the title, click on "T"-Button and select "Show Title"

_**Screenshot:**_
[(https://abload.de/img/pic_streamdeck_show_tb7j12.png)]

Kind regards
PythonInvasion

**Comment by ZerGo0** [comment]
> Hey there,
> 
> i have an issue with your ts3 streamdeck integration.
> 
> When i place the ts3 mute on my deck for example and I remove the title "TeamSpeak
> Mic Mute" of this deck icon so it has not title and then restart my PC/StreamDeck. Then after the restart the title is back there and I have to remove it manually.
> 
> Would it be possible for you to fix this little issue, because it is a bit exhausting to remove the title every time after a restart...

Seems to be a issue with the library that I use, for now either user the method mentioned above or just set the title to Space/New line.
