### ISSUE TITLE
can`t connect

### ISSUE THREAD

**Issue by WDDracones** [ZerGo0/streamdeck-teamspeak3integration#25]
Since yesterday I can no longer install the plug-in. When I try to install it, it seems to be uninstalled automatically. I can no longer use it as a result.

**Comment by ZerGo0** [comment]
Can you open the following path, right-click the file called `Newtonsoft.Json.dll` > Details and tell me what the `File version` is? ```%appdata%\Elgato\StreamDeck\Plugins\com.zergo0.teamspeak3integration.sdPlugin```
![img](https://i.imgur.com/oLhRuuF.png)

**Comment by WDDracones** [comment]
13.0.1.25517

**Comment by ZerGo0** [comment]
Semms to be correct, have you tried restarting Teamspeak and the Streamdeck software. An update was released last Sunday that updated that file, nothing else changed.

**Comment by ZerGo0** [comment]
Also, make sure that you have .Net Framework 4.8 installed.

**Comment by WDDracones** [comment]
Sorry... but it still doesn't work... do you have another idea how to fix it?

**Comment by ZerGo0** [comment]
Nothing major changed like I said, it could be another software interfering
with it and blocking the connection, Logitech Gaming Software for example.

It's also possible that some software like a antivirus is blocking the
connection of the plugin. Check if you can ping 127.0.0.1, and check if the
the plugin process is actually running. (Shown as
com.zergo0.teamspeak3integration in Task Manager)

This could be anything tho and I can't really tell you how to fix it. No
one else seems to have issues given that no one else reported anything
which means that the update didn't break anything.

**Comment by WDDracones** [comment]
Good day,

I have fixed the problem.
If someone has the problem: create a back-up of your profiles, delete ALL data from the StreamDeck from the computer (except the back-up, your icons etc), uninstall the driver and reinstall it. Then it will work again.

Thanks for the help! Super PlugIn!
