### ISSUE TITLE
Removed title not saving

### ISSUE THREAD

**Issue by maddingamer** [ZerGo0/streamdeck-teamspeak3integration#4]
I'm using the toggle input and output mute actions. 
I removed the title of them, as the icon itself looks cleaner to me. 
But sometimes, when restarting the software or making other changes to other buttons, the titles are reset to default (e.g. Toggle INPUT Mute shows it's name on the button insted of a clean icon only as before). Any way to improve saving the empty title? Or add a checkbox for hide title maybe?

Thx :)

**Comment by ZerGo0** [comment]
> I'm using the toggle input and output mute actions.
> I removed the title of them, as the icon itself looks cleaner to me.
> But sometimes, when restarting the software or making other changes to other buttons, the titles are reset to default (e.g. Toggle INPUT Mute shows it's name on the button insted of a clean icon only as before). Any way to improve saving the empty title? Or add a checkbox for hide title maybe?
> 
> Thx :)

Hey,

sorry for responding so late, kinda forgot about this. I'm pretty sure that I never set the title in the actions themselves so this might be a bug related to the library that I use. I will check it out next weekend and report back.

As a possible temp fix try to set the title to just a space or a unicode space, it might work, never tried it tho.

Thanks for reporting it.

**Comment by maddingamer** [comment]
As a workaround; using unicode space does the job as it seems (Regular space does not work tho)

**Comment by ZerGo0** [comment]
Hopefully able to check it out myself next weekend. Quite busy the past few weeks sadly.

**Comment by ZerGo0** [comment]
Found the "bug" and a way to prevent it, waiting for BarRaider's reply, might be intentional. Definitely not related to my plugin tho.

Removing the text from the first state and then the second state seems to "fix"/prevent it.
