### ISSUE TITLE
Author's Discord Disappeared

### ISSUE THREAD

**Issue by mknooihuisen** [ZerGo0/streamdeck-teamspeak3integration#5]
Hi ZerGo0!  I'm CyberlightGames from the BarRaider discord.  We noticed that you are no longer in the Discord and we're wondering what we should do with your plugin. Will you be rejoining?  Is the plugin abandoned?

**Comment by ZerGo0** [comment]
> Hi ZerGo0! I'm CyberlightGames from the BarRaider discord. We noticed that you are no longer in the Discord and we're wondering what we should do with your plugin. Will you be rejoining? Is the plugin abandoned?

Hey,

I have to sort a few things out with discord before I rejoin. I'm still actively developing it, the mandatory features are all in it and working as intended so there is no need to push a update. I could a a bunch more, but I haven't gotten around to test out new stuff.

Thanks for worrying

**Comment by ZerGo0** [comment]
Rejoined :)
