### ISSUE TITLE
Plugin reaction extreme slow

### ISSUE THREAD

**Issue by PythonInvasion** [ZerGo0/streamdeck-teamspeak3integration#7]
Hello. I don't know if you test your plugin. I downloaded it here from github and installed it.

The time until the command execute is extrem slow. I press the button (mute microphon) and 2 minutes (no joke) the status get executed.
I test some other commands from Default Stream Deck commands (write a text) - this will be instandly executed.

Have you change something ?

**Comment by ZerGo0** [comment]
> Hello. I don't know if you test your plugin. I downloaded it here from github and installed it.
> 
> The time until the command execute is extrem slow. I press the button (mute microphon) and 2 minutes (no joke) the status get executed.
> I test some other commands from Default Stream Deck commands (write a text) - this will be instandly executed.
> 
> Have you change something ?

I haven't changed anything, I only add actions which doesn't affect anything. I use it myself daily and I haven't experienced anything like it. Check the CPU Usage of Teamspeak when that happens, it is possible that the ClientQuery plugin is lagging or that another program is using it which will interfere with this.

**Comment by PythonInvasion** [comment]
After i closed the icon editor from Stream Deck the time to execution a command reduced < 1 second. It's kind of weird. Can you optimize the lead time a little more?

Otherwise the problem is solved.

**Comment by ZerGo0** [comment]
> After i closed the icon editor from Stream Deck the time to execution a command reduced < 1 second. It's kind of weird. Can you optimize the lead time a little more?
> 
> Otherwise the problem is solved.

It runs as fast as it possibly can, everything has to be run in 1 connection and in order, so when you press a button it might have to wait till the status updates are done and it will then execute the action, there is no way to change that. I originally had 1 connection per action/button which caused the Client Query plugin to overload and crash after a few hours, this is the only way of doing it sadly.
