### ISSUE TITLE
Strange behave with mute local microphon

### ISSUE THREAD

**Issue by PythonInvasion** [ZerGo0/streamdeck-teamspeak3integration#8]
I'm on Teamspeak 3-Channel with force "Push to Talk". Whem i add Teamspeak Mic Mute (Local) and press the button twice (with delay) the microphon opens until i press the Stream Deck key again.

My-push-to-talk button is (Left) Shift-key

**Comment by ZerGo0** [comment]
> I'm on Teamspeak 3-Channel with force "Push to Talk". Whem i add Teamspeak Mic Mute (Local) and press the button twice (with delay) the microphon opens until i press the Stream Deck key again.
> 
> My-push-to-talk button is (Left) Shift-key

That's just how it works, this is not the normal mic mute function, this the local one which is pretty hidden.

Bind it to a hotkey and test it yourself, that's how it works, it's not an issue related to my plugin.
