### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by DjSni** [ZerGo0/streamdeck-teamspeak3integration#9]
I am often on German Teamspeaks, but in German the "ö, ä, ü, ß" is often used in channel names so that the "Switch Channel" does not work.
It would be cool if the bug will be fixed.

**Comment by ZerGo0** [comment]
Sorry for the extremely late response, totally forgot about this. Sadly I can't fix that easily, the Telnet Libary that I use doesn't seem to support these kinds of characters which results in a channel name like this: https://i.imgur.com/GlbMD6o.png

I would've to either find another library or make my own, both options would take too much time, sorry. The next update will include support for channel ids, you should probably use that instead.
